[tool.kedro]
package_name = "pyspark_viz_spaceflights"
project_name = "pyspark-viz-spaceflights"
kedro_init_version = "0.18.12"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/pyspark_viz_spaceflights -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
